POST http://localhost:4000/auth/token

###
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "message": "test messageaaa",
  "email": "nhat.nguyen1125@gmail.com",
  "password": "Minhnhat34",
  "handle": "bbbbbbbb$",
  "name": "dddd ddd    ddd"
}

###